### ISSUE TITLE
Support for JSON EntityStreamingSupport and example needed

### ISSUE THREAD

**Issue by schrepfler** [knutwalker/akka-stream-json#5]
It's not clear to me if akka-stream-json can be used together with Source Streaming/JSON streaming as documented by http://doc.akka.io/docs/akka/2.4/scala/http/routing-dsl/source-streaming-support.html.
In particular I don't understand if the  framing done by akka-stream-json can work together with EntityStreamingSupport.json() (and the configuration of it) or is the framing done explicitly by akka-stream-json?
I think an example with a web socket client which opens a connection and streams entities would be useful to illustrate concretely the API's use, either with a concrete case class object or a general Json object, especially as there are not many example around (example, let's not just do the canonical Sink.foreach(println), can the example illustrate working with the case class)?

**Comment by knutwalker** [comment]
This is a new feature that was introduced in 2.4.9, I haven't even checked it out by myself yet. From a quick look at the docs and code, it seems like `EntityStreamingSupport.json()` provides basically the same functionality as this project, with the following differences:
- Akka uses a [flexible framing](https://github.com/akka/akka/blob/ee116dcdabbca97cd7fcb51c6b603945a726c8c5/akka-stream/src/main/scala/akka/stream/scaladsl/JsonFraming.scala#L16) based on a [custom parser](https://github.com/akka/akka/blob/ee116dcdabbca97cd7fcb51c6b603945a726c8c5/akka-stream/src/main/scala/akka/stream/impl/JsonObjectParser.scala#L14) to identify complete json objects and dispatches to the existing unmarshalling infrastructure for the actual parsing (which might use jackson, spray, jawn, ...)
- this project uses Jawns [async parsing](https://github.com/non/jawn#parsing) facilities and can be [configured accordingly](https://github.com/knutwalker/akka-stream-json/blob/master/stream-json/src/main/scala/de/knutwalker/akka/stream/JsonStreamParser.scala#L50)
- EntityStreamingSupport requires akka-http as a dependency, which is optional for akka-stream-json (though, I suspect most usages will have akka-http regardless)
- In terms of backpressure and integration into streams, both solutions seem to have similar capabilities, while EntityStreamingSupport has an explicit API for parallel unmarshalling

So, I don't think you can profit from combining these two options but have to choose one over the other. I agree though, that this project can do with some more examples.

**Comment by schrepfler** [comment]
I see, that would make sense. I guess we can close this ticket if the feature super-seeds it.
